### ISSUE TITLE
чуть больше информации в документации

### ISSUE THREAD

**Issue by ghost** [Zawullon/fpnativeapi#1]
а можно чуть расширить

* как собрать из исходников
* каков функционал

и т.д.

**Comment by Zawullon** [comment]
Извиняюсь, что не ответил сразу.
Постараюсь найти время для более подробного описания.
Если вкратце, то собирается, как обычный проект в Lazarus (открыть в IDE и вызвать Build). Этакий слегка расширенный аналог стандартного примера на C++ от 1C.
Предоставляет возможность писать на Lazarus полноценные NativeAPI-расширения для 1С, при этом работая со стандартными вариантами FPC и используя его объектную модель.
В зачаточном состоянии (написана, но практически не протестирована) возможность использования GUI на LCL. Тут стандартная проблема из-за того, что Lazarus рассчитан на работу с GUI в основном потоке приложения и это много где прописано.
Спасибо за замечания.

**Comment by Zawullon** [comment]
Написал описание. Сорри, что так долго - времени свободного совсем нет.
