### ISSUE TITLE
1С

### ISSUE THREAD

**Issue by Kazakoff64** [Zawullon/fpnativeapi#3]
Можно рабочие примеры как использовать в 1С.

**Comment by Zawullon** [comment]
Так в документации по 1с-же, вроде было:

ПодключитьВнешнююКомпоненту(ПутьКФайлуDLL, "ИмяКомпоненты", ТипВнешнейКомпоненты.Native);
ОбъектКомпоненты = Новый("AddIn.ИмяКомпоненты.AddInNativeExtension")

Код тут повторяет стандартный пример из ИТС с таймером в C-like стиле (example.pas, AddInNativeExtension), плюс пример тех же возможностей с более простым написанием кода (easyexample.pas, AddInNativeEasyExtension). Т.е. это именно шаблон для разработки своих компонент. GUI пока просто в виде ProofOfConcept, т.е. лучше будет просто удалить v8addingui.pas из проекта. Ну и нет возможности пока даже посмотреть на проблему с Linux (issue #2), т.к. дома нет возможности установить 1С, а на работе под Linux  только production-сервер, его крашить не могу.

**Comment by Kazakoff64** [comment]
Вот я именно про "ИмяКомпоненты" что именно писать я уже все перепробовал

**Comment by Zawullon** [comment]
Так оно произвольное.
Под этим именем оно будет зарегистрировано в 1С и его надо будет подставлять в имя класса Новый("AddIn.<вот тут оно>.AddInNativeExtension")
А AddInNativeExtension берется из RegisterExtensionAs при C-like стиле написания или указывается при вызове RegisterAddInClass в Easy-варианте (см. AddInNative.lpr)

**Comment by Zawullon** [comment]
У меня для тестов использовался следующий код: 

&НаКлиенте
Перем AddInNativeExtension, AddInNativeEasyExtension, AddInNativeGUIExtension;

&НаКлиенте
Процедура ПриОткрытии(Отказ)
	Результат = ПодключитьВнешнююКомпоненту("D:\Develop\fpnativeapi\AddInNative.dll", "AddInNative", ТипВнешнейКомпоненты.Native);
	AddInNativeExtension = Новый("AddIn.AddInNative.AddInNativeExtension");
	AddInNativeEasyExtension = Новый("AddIn.AddInNative.AddInNativeEasyExtension");
	AddInNativeGUIExtension = Новый("AddIn.AddInNative.AddInNativeGUIExtension");
КонецПроцедуры

**Comment by Kazakoff64** [comment]
Блин все равно
Тип не определен (AddIn.AddInNative.AddInNativeExtension)
	AddInNativeExtension = Новый("AddIn.AddInNative.AddInNativeExtension");

**Comment by Zawullon** [comment]
а вызов RegisterAddInClass или RegisterAddInClass в .lpr есть? Версия 1С? Клиент или сервер, разрядность?

**Comment by Zawullon** [comment]
И версию FPC/Lazarus, если можно

**Comment by Zawullon** [comment]
Немного исправил для сборки в Lazarus 1.8.0 и добавил внешнюю обработку с примером использования (1с 8.3, управляемые формы).

**Comment by Zawullon** [comment]
Отпишитесь, что получится.

**Comment by Kazakoff64** [comment]
Отлично все работает только я в обработке закомментировал вот это 

```
&НаСервере
Процедура ПриСозданииНаСервере(Отказ, СтандартнаяОбработка)
	
	//ФормыСервер.ПриСозданииФормы(ЭтотОбъект, Перечисления.ТипыФорм.ФормаОбработки);
		
КонецПроцедуры
```
Выходит ошибка

**Comment by Kazakoff64** [comment]
Еще вопрос а на стороне сервера она будет работать??? что бы вызвать метод с клиента?

**Comment by Zawullon** [comment]
В обработке забыл убрать этот кусок, сорри.
Если не использовать GUI (или просто убрать его), то на сервере 1С для Windows будет работать для 32-бит, на 64-бит - скорее всего, но не тестил, у меня только 32-битный сервер 1С. Под Linux пишут, что вылетает. Видимо, у GCC и VCC разная реализация классов, т.к. "pure C" вызовы должны нормально работать и там, и там, я их уже реализовывал в других проектах.
Ну и само собой для использования на сервере, ее там и подключать надо будет.

**Comment by Kazakoff64** [comment]
Пока мне не удалось запустить на 64битном сервере, попробую для начала на 32битном.

**Comment by Zawullon** [comment]
Для 64-бит надо отдельную DLL собирать. Вроде, в параметрах сборки проекта изменить целевое семейство процессоров на x86_64. Соответственно, сборки FPC и Lazarus тоже должны быть 64-битными.

**Comment by Kazakoff64** [comment]
Спасибо, все работает.
