### ISSUE TITLE
GetInterface

### ISSUE THREAD

**Issue by theprogrammer67** [Zawullon/fpnativeapi#5]
Не подскажете, почему GetInterface(FConnection, eIMsgBox) возвращает указатель смещенный на один элемент вперед? И приходится делать декремент: GetInterface(FConnection, eIMsgBox) - SizeOf(Pointer)?
Столкнулся сам с этим в собственной разработке на Delphi. Решил аналогичным способом. Но хотелось бы понять причину!
Спасибо!

**Comment by Zawullon** [comment]
Ссылка на экземпляр класса указывает на начало его данных, но перед данными еще есть указатель на таблицу виртуальных методов (VTable) класса. Поэтому приходится сдвигать указатель на размер этого указателя, т.к. он тоже является частью представления объекта в памяти.
